nursery/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('frontend.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager,AbstractUser

class CustomUserManager(BaseUserManager):
    
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, password, **extra_fields)

class Users(AbstractUser):
    username = None  # Remove the username field

    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30,null=True,blank=True)

    # Add your additional fields here
    date_of_birth = models.DateField(null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name']  # Add any other required fields

    objects = CustomUserManager()

    def __str__(self):
        return self.email


class Company(models.Model):
    class Meta:
        db_table = "company"
        verbose_name = 'Company'
        verbose_name_plural = 'Companies'

    name = models.CharField(max_length=255)
    description = models.TextField(null=True,blank=True)
    email = models.CharField(max_length = 255)
    phone_number = models.CharField(max_length = 14)
    logo = models.ImageField(upload_to='logo/',null=True,blank=True)
    favicon = models.ImageField(upload_to='favicon/',null=True,blank=True)
    address = models.CharField(max_length = 255,null=True,blank=True)
    currency_symbol = models.TextField(blank=True,default="₹")

    def __str__(self):
        return self.name

class ProductCategory(models.Model):

    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'ProductCategory'
        verbose_name_plural = 'ProductCategories'

    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='categories/',blank=True,default='/categories/default-image.png')
    show_on_home = models.BooleanField(default=False,blank=True)

    def __str__(self):
        return self.name


class Products(models.Model):

    class Meta:
        db_table = 'products'
        managed = True
        verbose_name = 'Product'
        verbose_name_plural = 'Products'
    
    name = models.CharField(max_length=255)
    category = models.ForeignKey(ProductCategory,on_delete=models.PROTECT,null=True,blank=True)
    cost_price = models.CharField(max_length=255)
    selling_price = models.CharField(max_length=255)
    rating = models.CharField(max_length=255,null=True,blank=True)
    short_description = models.CharField(max_length=255)
    description = models.TextField()
    tags = models.CharField(max_length = 255,null=True,blank=True)
    is_published = models.BooleanField(default=True,null=True,blank=True)
    is_new_arrival = models.BooleanField(default=True,null=True,blank=True)
    is_best_selling = models.BooleanField(default=True,null=True,blank=True)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

class Images(models.Model):
    class Meta:
        db_table = 'images'
        managed = True
        verbose_name = 'Image'
        verbose_name_plural = 'Images'
    
    image = models.ImageField(upload_to='images/')
    product = models.ForeignKey(Products,on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.product.name} (path = {self.image})"

class ProductCollections(models.Model):

    class Meta:
        db_table = 'product_collections'
        managed = True
        verbose_name = 'Product Collection'
        verbose_name_plural = 'Product Collections'

    name = models.CharField(max_length=255,unique=True)
    product_ids = models.CharField(max_length=255)
    is_published = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class HomepageCollection(models.Model):

    class Meta:
        db_table = 'homepage_collection'
        managed = True
        verbose_name = 'Homepage Collection'
        verbose_name_plural = 'Homepage Collections'

    collection = models.ForeignKey(ProductCollections,on_delete=models.PROTECT)

    def __str__(self):
        return self.collection.name

class Banner(models.Model):

    class Meta:
        db_table = 'banners'
        managed = True
        verbose_name = 'Banner'
        verbose_name_plural = 'Banners'

    image = models.ImageField(upload_to='banners/')
    heading = models.CharField(max_length=255,null=True,blank=True)
    sub_heading = models.CharField(max_length=255,null=True,blank=True)
    title = models.CharField(max_length=255,null=True,blank=True)

    def __str__(self):
        return (f"{self.title} (path = {self.image})")


class ShopByCategory(models.Model):
    class Meta:
        db_table = "shop_by_category"
        managed = True
        verbose_name = 'Shop By Category'
        verbose_name_plural = 'Shop By Categories'

    product = models.ForeignKey(Products,on_delete=models.CASCADE)

    def __str__(self):
        return self.product.name


class Cart(models.Model):
    class Meta:
        db_table = "cart"
        verbose_name = 'Cart'
        verbose_name_plural = 'Carts'

    product = models.ForeignKey(Products,on_delete=models.CASCADE)
    quantity = models.CharField(max_length = 255,default=1,blank=True)
    total = models.CharField(max_length = 255,null=True,blank=True)
    # discount = models.CharField(max_length = 255,null=True,blank=True)
    user = models.ForeignKey(Users,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.email


class UserAddress(models.Model):
    class Meta:
        db_table = "UserAddress"
        verbose_name = 'User Address'
        verbose_name_plural = 'User Addresses'

    user = models.ForeignKey(Users,on_delete = models.CASCADE)
    first_name = models.CharField(max_length = 255)
    last_name = models.CharField(max_length = 255,null=True,blank=True)
    email = models.EmailField()
    company_name = models.CharField(max_length= 255,null=True,blank=True)
    address = models.CharField(max_length = 255)
    city = models.CharField(max_length = 255)
    state = models.CharField(max_length=255)
    order_notes = models.TextField(null=True,blank=True)
    country = models.CharField(max_length = 255)
    pin_code = models.CharField(max_length = 20)
    phone_number = models.CharField(max_length = 255)

    def __str__(self):
        return self.user.email


class Orders(models.Model):
    class Meta:
        db_table = "orders"
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'


    user = models.ForeignKey(Users,on_delete=models.CASCADE)
    address = models.ForeignKey(UserAddress,on_delete = models.CASCADE)
    products = models.TextField()
    total_price = models.CharField(max_length = 255)
    date_time = models.CharField(max_length = 255)
    is_completed = models.BooleanField(default=False,null=True,blank=True) 

    def __str__(self):
        return self.user.email
    

class Newsletters(models.Model):
    class Meta:
        db_table = 'newsletters'
        verbose_name = 'Newsletter'
        verbose_name_plural = 'Newsletters'

    email = models.EmailField()
    date_time = models.CharField(max_length = 255,blank=True,null=True)
    is_approved = models.BooleanField(default=False,null=True,blank=True)

    def __str__(self):
        return self.email


class Contact(models.Model):
    class Meta:
        db_table = "contact"
        verbose_name = 'Contact'
        verbose_name_plural = 'Contacts'

    name = models.CharField(max_length= 255)
    email = models.EmailField()
    subject = models.CharField(max_length = 255)
    message = models.TextField()
    date_time = models.CharField(max_length = 255,null=True,blank=True)
    is_read = models.BooleanField(default = False,null=True,blank=True)

    def __str__(self):
        return f"{self.name} - {self.date_time}"


class Reviews(models.Model):
    class Meta:
        db_table = "reviews"
        verbose_name = 'Review'
        verbose_name_plural = 'Reviews'

    user = models.ForeignKey(Users,on_delete=models.CASCADE,blank=True)
    product = models.ForeignKey(Products,on_delete=models.CASCADE,blank=True)
    nickname = models.CharField(max_length = 255)
    reason = models.CharField(max_length = 255)
    comments = models.TextField()
    rating = models.CharField(max_length = 255)
    date_time = models.CharField(max_length = 255)
    is_read = models.BooleanField(default=False,null=True,blank=True)

    def __str__(self):
        return f"{self.user.email} - {self.date_time}"

class Blogs(models.Model):
    class Meta:
        db_table = "blogs"
        verbose_name = 'Blog'
        verbose_name_plural = 'Blogs'

    user = models.ForeignKey(Users,on_delete = models.CASCADE)
    publish_date = models.CharField(max_length = 255)
    title = models.CharField(max_length = 255)
    description = models.TextField()
    is_published = models.BooleanField(default = True,blank=True,null=True)

    def __str__(self):
        return f"{self.user.email} - {self.title}"

class BlogComments(models.Model):
    class Meta:
        db_table = "blog_comments"
        verbose_name = 'Blog Comment'
        verbose_name_plural = 'Blog Comments'

    user = models.ForeignKey(Users,on_delete=models.CASCADE)
    blog = models.ForeignKey(Blogs,on_delete=models.CASCADE)
    name = models.CharField(max_length = 255)
    email = models.EmailField()
    comment = models.TextField()
    tags = models.CharField(max_length = 255,null=True,blank=True)
    is_approved = models.BooleanField(default = False,blank=True,null=True)

    def __str__(self):

backend/forms.py
from django import forms
from .models import *


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = "__all__"

class ImagesForm(forms.ModelForm):
    class Meta:
        model = Images
        fields = [
            "image"
            ]
        exclude = ["product"]

class ProductForm(forms.ModelForm):
    class Meta:
        model = Products
        fields = "__all__"


class BannerForm(forms.ModelForm):
    class Meta:
        model = Banner
        fields = "__all__"


class CategoryForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = "__all__"

backend/templates/edit/banner.html
{% extends "masters/admin_master.html" %}

{% block title %}
  Edit Banner
{% endblock title %}

{% block page-name %}
  Edit Banner
{% endblock page-name %}

{% block body %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<style>
    .add-product-section-43264 .container {
        max-width: 90%;
        margin: 50px auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    .add-product-section-43264 h2 {
        text-align: center;
    }
    .add-product-section-43264 form {
        margin-top: 20px;
    }
    .add-product-section-43264 label {
        font-weight: bold;
    }
    .add-product-section-43264 input[type="text"],
    .add-product-section-43264 input[type="number"],
    select,
    .add-product-section-43264 textarea {
        width: 100%;
        padding: 10px;
        margin-top: 5px;
        margin-bottom: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
    }
    .add-product-section-43264 input[type="file"] {
        margin-top: 5px;
        margin-bottom: 20px;
    }
    .add-product-section-43264 .image-preview {
        text-align: center;
        margin-bottom: 20px;
    }
    .add-product-section-43264 .image-preview img {
        max-width: 200px;
        max-height: 200px;
        border-radius: 5px;
        margin-top: 10px;
    }
    .add-product-section-43264 input[type="submit"] {
        background-color: #4CAF50;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        width: 100%;
    }
    .add-product-section-43264 input[type="submit"]:hover {
        background-color: #45a049;
    }
    .preview-container{
        display: flex;
        gap: 10px;
        flex-wrap: wrap;
    }
    .preview-container .image-preview{
        border: solid 1px rgb(172, 172, 172);
    }
</style>
<div class="add-product-section-43264">
<div class="container">
<h2>Banner Form</h2>
<form action="{%url 'edit-banner' banner_id=banner.id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="name">Title:</label><br>
    <input type="text" id="name" name="title" value="{{banner.title}}"><br>

    <label for="name">Heading:</label><br>
    <textarea id="heading" name="heading">{{banner.heading}}</textarea><br>
    
    <label for="name">Sub Heading:</label><br>
    <textarea id="sub_heading" name="sub_heading" >{{banner.sub_heading}}</textarea><br>

    <label for="image">Image:</label><br>
    <input type="file" id="id_image" name="image"><br>
    {% if banner.image %}
        <img src="/media/{{banner.image}}" id="image_preview" alt="" width="50%">
        {%else%}  
        <img src="" id="image_preview" alt="" width="50%">
    {% endif %}

    <input type="submit" value="Submit">
</form>
</div>
</div>
<script>
    $(document).ready(function() {
        $('#id_image').change(function() {  // Assuming your file input field has id="id_image"
            var input = this;
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#image_preview').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        });
    });
    </script>
{% endblock body %}

backend/templates/edit/company.html
{% extends "masters/admin_master.html" %}

{% block title %}
  Edit Company
{% endblock title %}

{% block page-name %}
  Company
{% endblock page-name %}

{% block body %}
<!-- <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/6.8.3/tinymce.min.js" integrity="sha512-VCEWnpOl7PIhbYMcb64pqGZYez41C2uws/M/mDdGPy+vtEJHd9BqbShE4/VNnnZdr7YCPOjd+CBmYca/7WWWCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        tinymce.init({
            selector: '#description',
            plugins: 'advlist autolink lists link image charmap print preview anchor',
            toolbar: 'undo redo | formatselect | bold italic underline | alignleft aligncenter alignright | bullist numlist outdent indent | link image'
        });
        tinymce.init({
            selector: '#short_description',
            plugins: 'advlist autolink lists link image charmap print preview anchor',
            toolbar: 'undo redo | formatselect | bold italic underline | alignleft aligncenter alignright | bullist numlist outdent indent | link image'
        });
    </script>
<style>
    .add-product-section-43264 .container {
        max-width: 90%;
        margin: 50px auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    .add-product-section-43264 h2 {
        text-align: center;
    }
    .add-product-section-43264 form {
        margin-top: 20px;
    }
    .add-product-section-43264 label {
        font-weight: bold;
    }
    .add-product-section-43264 input[type="text"],
    .add-product-section-43264 input[type="number"],
    select,
    textarea,
    .add-product-section-43264 textarea {
        width: 100%;
        padding: 10px;
        margin-top: 5px;
        margin-bottom: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
    }
    .add-product-section-43264 input[type="file"] {
        margin-top: 5px;
        margin-bottom: 20px;
    }
    .add-product-section-43264 .image-preview {
        text-align: center;
        margin-bottom: 20px;
    }
    .add-product-section-43264 .image-preview img {
        max-width: 200px;
        max-height: 200px;
        border-radius: 5px;
        margin-top: 10px;
    }
    .add-product-section-43264 input[type="submit"] {
        background-color: #4CAF50;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        width: 100%;
    }
    .add-product-section-43264 input[type="submit"]:hover {
        background-color: #45a049;
    }
    .preview-container{
        display: flex;
        gap: 10px;
        flex-wrap: wrap;
    }
    .preview-container .image-preview{
        border: solid 1px rgb(172, 172, 172);
    }
</style>
<div class="add-product-section-43264">
<div class="container">
<h2>Company Form</h2>
<form action="{%url 'edit-company'%}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="name">Name:</label><br>
    <input type="text" id="name" name="name" value="{{company.name}}" required><br>
    
    <label for="name">Description:</label><br>
    <textarea id="id_description" name="description" >{{company.description | safe}}</textarea><br>
    
    <label for="name">Phone Number (+91):</label><br>
    <input type="text" id="id_phone_number" name="phone_number" value="{{company.phone_number}}" required><br>
    
    <label for="name">Address:</label><br>
    <input type="text" id="id_address" name="address" value="{{company.address}}"><br>
    
    <label for="name">Email:</label><br>
    <input type="email" id="id_email" name="email" value="{{company.email}}" required><br>

    <label for="image">Logo:</label><br>
    <input type="file" id="id_logo" name="logo" ><br>
        {% if company.logo %}
            <img id="id_preview_image1" src="/media/{{company.logo}}" style="max-width: 300px;max-height: 300px;">
        {%else%}
            <img id="id_preview_image1" src="" alt="" style="max-width: 300px;max-height: 300px;">
        {% endif %}
    <br>
    <label for="image">Favicon:</label><br>
    <input type="file" id="id_favicon" name="favicon"><br>
        {% if company.favicon %}
            <img src="/media/{{company.favicon}}" alt="" style="max-width: 300px;max-height: 300px;">
        {%else%}
            <img src="" alt="" style="max-width: 300px;max-height: 300px;">
        {% endif %}
`

    <input type="submit" value="Submit">
</form>
</div>
</div>
<script>
document.getElementById('id_logo').addEventListener('change', function(event) {
    console.log("changed");
      var file = event.target.files[0];
      var reader = new FileReader();

      reader.onload = function(event) {
        // document.getElementById('id_preview_image1').style.display = 'block'; // Show the image preview
        document.getElementById('id_preview_image1').src = event.target.result;
      };

      reader.readAsDataURL(file);
    });
</script>
{% endblock body %}

backend/templates/edit/product.html
{% extends "masters/admin_master.html" %}

{% block title %}
  Edit Product - {{product.name}}
{% endblock title %}

{% block page-name %}
  Edit - {{product.name}}
{% endblock page-name %}

{% block body %}
<!-- <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/6.8.3/tinymce.min.js" integrity="sha512-VCEWnpOl7PIhbYMcb64pqGZYez41C2uws/M/mDdGPy+vtEJHd9BqbShE4/VNnnZdr7YCPOjd+CBmYca/7WWWCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        tinymce.init({
            selector: '#description',
            plugins: 'advlist autolink lists link image charmap print preview anchor',
            toolbar: 'undo redo | formatselect | bold italic underline | alignleft aligncenter alignright | bullist numlist outdent indent | link image'
        });
        tinymce.init({
            selector: '#short_description',
            plugins: 'advlist autolink lists link image charmap print preview anchor',
            toolbar: 'undo redo | formatselect | bold italic underline | alignleft aligncenter alignright | bullist numlist outdent indent | link image'
        });
    </script>
<style>
    .add-product-section-43264 .container {
        max-width: 90%;
        margin: 50px auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    .add-product-section-43264 h2 {
        text-align: center;
    }
    .add-product-section-43264 form {
        margin-top: 20px;
    }
    .add-product-section-43264 label {
        font-weight: bold;
    }
    .add-product-section-43264 input[type="text"],
    .add-product-section-43264 input[type="number"],
    select,
    .add-product-section-43264 textarea {
        width: 100%;
        padding: 10px;
        margin-top: 5px;
        margin-bottom: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
    }
    .add-product-section-43264 input[type="file"] {
        margin-top: 5px;
        margin-bottom: 20px;
    }
    .add-product-section-43264 .image-preview {
        text-align: center;
        margin-bottom: 20px;
    }
    .add-product-section-43264 .image-preview img {
        max-width: 200px;
        max-height: 200px;
        border-radius: 5px;
        margin-top: 10px;
    }
    .add-product-section-43264 input[type="submit"] {
        background-color: #4CAF50;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        width: 100%;
    }
    .add-product-section-43264 input[type="submit"]:hover {
        background-color: #45a049;
    }
    .preview-container{
        display: flex;
        gap: 10px;
        flex-wrap: wrap;
    }
    .preview-container .image-preview{
        border: solid 1px rgb(172, 172, 172);
    }
</style>
<div class="add-product-section-43264">
<div class="container">
<h2>Product Form</h2>
<form action="{%url 'edit-product' product_id=product.id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="name">Name:</label><br>
    <input type="text" id="name" name="name" value="{{product.name}}"><br>

    <label for="category">Category:</label><br>
    <select name="category" id="category" required>
        <option value="--">--</option>
        {% for category in categories %}
        {% if product.category.id == category.id %}
            <option value="{{category.id}}" selected>{{category.name}}</option>
        {%else%}
            <option value="{{category.id}}">{{category.name}}</option>
        {% endif %}
        {% endfor %}
    </select>

    <label for="cost_price">Cost Price:</label><br>
    <input type="text" id="cost_price" name="cost_price" value="{{product.cost_price}}" required><br>

    <label for="selling_price">Selling Price:</label><br>
    <input type="text" id="selling_price" name="selling_price" value="{{product.selling_price}}" required><br>

    <label for="short_description">Short Description:</label><br>
    <textarea id="short_description" name="short_description" rows="4">{{product.short_description | safe}}</textarea><br>

    <label for="description">Description:</label><br>
    <textarea id="description" name="description" rows="8" >{{product.description | safe}}</textarea><br>

    <label for="image">Image:</label><br>
    <input type="file" id="images" name="images" accept="image/*" multiple onchange="previewImages(event)"><br>

        <div class="preview-container" id="previewContainer">

                {% for image in images %}
                  <img src="/media/{{image.image}}" alt="image" class="image-preview">
                {% endfor %}
        </div>

        <label for="is_best_selling">Include in Best Selling?</label>
        <select name="is_best_selling" id="is_best_selling">
        {% if product.is_best_selling %}
        <option value="True" selected>Yes</option>
        <option value="False">No</option>
        {%else%}
        <option value="True">Yes</option>
        <option value="False" selected>No</option>
        {% endif %}
    </select>
      

    <label for="is_new_arrival">New Arrival</label>
    <select name="is_new_arrival" id="is_new_arrival">
        {% if product.is_new_arrival %}
        <option value="True" selected>Yes</option>
        <option value="False">No</option>
        {%else%}
        <option value="True">Yes</option>
        <option value="False" selected>No</option>
        {% endif %}
    </select>

    <label for="is_published">Publish:</label><br>
    <select name="is_published" id="is_published">
        {% if product.is_published %}
        <option value="True" selected>Yes</option>
        <option value="False">No</option>
        {%else%}
        <option value="True">Yes</option>
        <option value="False" selected>No</option>
        {% endif %}
    </select>

    <input type="submit" value="Save">
</form>
</div>
</div>
<script>
function previewImages(event) {
        var previewContainer = document.getElementById('previewContainer');
        previewContainer.innerHTML = '';

        var files = event.target.files;
        for (var i = 0; i < files.length; i++) {
            var file = files[i];
            var reader = new FileReader();

            reader.onload = function(event) {
                var imagePreview = document.createElement('div');
                imagePreview.className = 'image-preview';
                var image = document.createElement('img');
                image.src = event.target.result;
                imagePreview.appendChild(image);
                previewContainer.appendChild(imagePreview);
            }

            reader.readAsDataURL(file);
        }
    }
</script>
{% endblock body %}